name: Deploy Flask Freeze to GitHub Pages

on:
  push:
    branches: ["main"]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build-and-deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del codice
        uses: actions/checkout@v4

      - name: Configura Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Installa dipendenze
        run: |
          python -m pip install --upgrade pip
          pip install flask Frozen-Flask

      - name: Esegui il Build statico
        run: python freeze.py

      - name: Carica artefatto per GitHub Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'build/'

      - name: Deploy su GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
